name: Force push most recent commit to trigger openshift-ci to rebuild images
on:
  workflow_dispatch:
    inputs:
      select_repo:
        description: 'Select a Repository'
        required: true
        type: choice
        options:
          - 'openvino_model_server'
          - 'kserve'
          - 'modelmesh'
          - 'caikit-tgis-serving'
          - 'openvino'
          - 'vllm'
          - 'caikit-nlp'
          - 'caikit'
          - 'odh-model-controller'
          - 'caikit-tgis-backend'
          - 'caikit-nlp-client'
          - 'model-registry'
      select_branch:
        description: 'downstream_branch branch to Force-push the amended commit'
        required: true
      select_midstream_or_downstream:
        description: 'Select midstream_or_downstream Repository to Force push most recent commit'
        required: true
        type: choice
        options:
          - 'Midstream(opendatahub-io)'
          - 'Downstream(red-hat-data-services)'
permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  create-upstream-pr:
    runs-on: ubuntu-latest
    outputs: 
        upstream_repo: ${{ steps.set-repo.outputs.upstream_org_repo }}
        midstream_repo: ${{ steps.set-repo.outputs.downstream_org_repo }}
    steps:
    - name: Set repository
      id: set-repo
      run: |
        if [[ "${{ github.event.inputs.select_midstream_or_downstream }}" == "Midstream(opendatahub-io)" ]]; then
          # echo "target_org_repo=opendatahub-io/${{ github.event.inputs.select_repo }}" >> $GITHUB_OUTPUT
          echo "target_org_repo=rpancham/${{ github.event.inputs.select_repo }}" >> $GITHUB_OUTPUT
        else
          # echo "target_org_repo=red-hat-data-services/${{ github.event.inputs.select_repo }}" >> $GITHUB_OUTPUT
          echo "target_org_repo=rpancham/${{ github.event.inputs.select_repo }}" >> $GITHUB_OUTPUT
        fi
    - name: Configure Git & install hub
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        repository: ${{ steps.set-repo.outputs.target_org_repo }}
        token: ${{ secrets.SYNC_UPSTREAM_TOKEN }}

    - name: Amend the last commit & Force-push the amended commit
      run: |
        git fetch --unshallow
        git commit --amend --no-edit
        git push --force-with-lease origin ${{ github.event.inputs.select_branch }}
      env:
        GITHUB_TOKEN: ${{ secrets.SYNC_UPSTREAM_TOKEN }}
